### PR TITLE
fix iOS Safari/Chrome input issue with focus and keyboard

### PR DESCRIPTION
**Pull request by OlehMarchenko95**
On **iOS** Safari/Chrome with version **12.3.1/12.4/13** **TextField** (input) fixed **Focus** and **Keyboard appearing** as per issues [#32763](https://github.com/flutter/flutter/issues/32763) and [#33011](https://github.com/flutter/flutter/issues/33011)

### CODE REVIEW

**Comment by OlehMarchenko95** [comment]
@googlebot I signed it!

**Comment by kevmoo** [comment]
CC @ferhatb @yjbanov

**Comment by uKL** [comment]
I hope this gets merged soon :) I can confirm that it works in out case.

**Comment by dbacinski** [comment]
I hope this will get merged soon. We have switched to this fork to have usable iOS inputs :)

**Comment by Sekaiichi4** [comment]
As I have no idea how to fork, can this be merged quickly? This bug is kinda holding me back from development. @ferhatb @OlehMarchenko95  Thanks in advance!

**Comment by OlehMarchenko95** [comment]
> As I have no idea how to fork, can this be merged quickly? This bug is kinda holding me back from development. @ferhatb @OlehMarchenko95 Thanks in advance!

@Sekaiichi4 you can replace dependency overrides section with this in order to use this pull request
```
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/OlehMarchenko95/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/OlehMarchenko95/flutter_web
      path: packages/flutter_web_ui
```

**Comment by Sekaiichi4** [comment]
> > As I have no idea how to fork, can this be merged quickly? This bug is kinda holding me back from development. @ferhatb @OlehMarchenko95 Thanks in advance!
> 
> @Sekaiichi4 you can replace dependency overrides section with this in order to use this pull request
> 
> ```
> dependency_overrides:
>   flutter_web:
>     git:
>       url: https://github.com/OlehMarchenko95/flutter_web
>       path: packages/flutter_web
>   flutter_web_ui:
>     git:
>       url: https://github.com/OlehMarchenko95/flutter_web
>       path: packages/flutter_web_ui
> ```

Thank you for your reply, I managed to replace my dependency overrides, but after making a new build and test it in the iOS browsers, I still have the same issues with the TextInputs not focussing right, and being unable to type anything. Is there maybe a step I have missed?

**Comment by dbacinski** [comment]
There is a chance that you have old version of flutter web which is cached. Run `pub get` and check which commit hash you are using.

**Comment by Sekaiichi4** [comment]
> There is a chance that you have old version of flutter web which is cached. Run `pub get` and check which commit hash you are using.

Hm... it seems that I am on commit 15c155, which should be the latest one if I'm not mistaken.

**Comment by OlehMarchenko95** [comment]
> > There is a chance that you have old version of flutter web which is cached. Run `pub get` and check which commit hash you are using.
> 
> Hm... it seems that I am on commit 15c155, which should be the latest one if I'm not mistaken.

Try to delete in your flutter repo cached packages

**Comment by Sekaiichi4** [comment]
> > > There is a chance that you have old version of flutter web which is cached. Run `pub get` and check which commit hash you are using.
> > 
> > 
> > Hm... it seems that I am on commit 15c155, which should be the latest one if I'm not mistaken.
> 
> Try to delete in your flutter repo cached packages
> It's in flutter.pub-cache\git folder, normally what I do is simply deleting all contents of its folder

Thank you for your reply, but this still didn't do the trick. even though my TextFields/TextFormFields are focussed, I can not enter any text in them...but sometimes I can q.q, almost seems completely random.

**Comment by OlehMarchenko95** [comment]
> > > > There is a chance that you have old version of flutter web which is cached. Run `pub get` and check which commit hash you are using.
> > > 
> > > 
> > > Hm... it seems that I am on commit 15c155, which should be the latest one if I'm not mistaken.
> > 
> > 
> > Try to delete in your flutter repo cached packages
> > It's in flutter.pub-cache\git folder, normally what I do is simply deleting all contents of its folder
> 
> Thank you for your reply, but this still didn't do the trick. even though my TextFields/TextFormFields are focussed, I can not enter any text in them...but sometimes I can q.q, almost seems completely random.

Could you share your code, I'll check it on my PC to figure out whats wrong

**Comment by Sekaiichi4** [comment]
> > > > > There is a chance that you have old version of flutter web which is cached. Run `pub get` and check which commit hash you are using.
> > > > 
> > > > 
> > > > Hm... it seems that I am on commit 15c155, which should be the latest one if I'm not mistaken.
> > > 
> > > 
> > > Try to delete in your flutter repo cached packages
> > > It's in flutter.pub-cache\git folder, normally what I do is simply deleting all contents of its folder
> > 
> > 
> > Thank you for your reply, but this still didn't do the trick. even though my TextFields/TextFormFields are focussed, I can not enter any text in them...but sometimes I can q.q, almost seems completely random.
> 
> Could you share your code, I'll check it on my PC to figure out whats wrong


Thank you for your assistance, I'll share my code on here (if that's ok) in case someone else stumbles on the same issue.

`
import 'package:flutter_web/material.dart';
import 'package:sherpa_cti/globals.dart' as globals;
import 'dart:html' as html;
import 'package:platform_detect/platform_detect.dart';

class LoginPage extends StatefulWidget {
  static String tag = 'login-page';
  @override
  _LoginPageState createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  // Create a text controller and use it to retrieve the current value
  // of the TextFields.
  var myCompanyController;
  var myUserController;
  var myPasswordController;

  bool loggingIn = false;
  bool failed = false;
  int _currentStep = 0;

  FocusNode companyField = FocusNode();
  FocusNode userField = FocusNode();
  FocusNode passwordField = FocusNode();

  void initState() {
    super.initState();
    myCompanyController = TextEditingController();
    myUserController = TextEditingController();
    myPasswordController = TextEditingController();
    // myCompanyController.text = " ";
    // myUserController.text = " ";
    // myPasswordController.text = " ";

    // companyField.addListener(changeFocus);
    // userField.addListener(changeFocus);
    // passwordField.addListener(changeFocus);
  }

  logInToServer() async {
    //Removed for Privacy's sake.
  }

  onLoggedInSuccess() {
    loggingIn = false;
    if (browser.isSafari) {
      setState(() {
        print("Is Safari...");
      });
    } else {
      print("Is NOT Safari...");
      Navigator.of(context).pop();
    }
  }

  onLoggedInFail() {
    setState(() {
      loggingIn = false;
      failed = true;
    });
  }

  changeFocus() {
    FocusScope.of(context).unfocus();

    if (companyField.hasFocus) {
      companyField.unfocus();
    } else if (userField.hasFocus) {
      // FocusScope.of(context).requestFocus(passwordField);
      userField.unfocus();
    } else if (passwordField.hasFocus) {
      passwordField.unfocus();
    }
  }

  @override
  void dispose() {
    // Clean up the controller when the widget is disposed.
    myCompanyController.dispose();
    myUserController.dispose();
    myPasswordController.dispose();

    companyField.dispose();
    userField.dispose();
    passwordField.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    print("Building");

    final errorText = Text(
      "Wrong credentials.",
      style: TextStyle(color: Colors.red[700]),
    );

    final progress = CircularProgressIndicator();

    final logo = Hero(
      tag: 'hero',
      child: globals.loggedIn
          ? CircleAvatar(
              backgroundColor: Colors.transparent,
              backgroundImage: NetworkImage(globals.yourImage),
              radius: 48.0,
            )
          : CircleAvatar(
              backgroundColor: Colors.transparent,
              radius: 48.0,
              child: Image.asset('/GUI/Icons/ico_user_seat.png'),
            ),
    );

    final company = TextFormField(
      controller: myCompanyController,
      keyboardType: TextInputType.number,
      autofocus: _currentStep == 0 ? true : false,
      focusNode: companyField,
      textInputAction: TextInputAction.next,
      // onEditingComplete: () {
      //   print("Editing company complete");
      // },
      // onTap: () {
      //   // if (companyField.hasFocus) {
      //   //   print("companyField has focus");
      //   // } else {
      //   //   FocusScope.of(context).requestFocus(companyField);
      //   // }
      //   setState(() {
      //     _currentStep = 0;
      //   });
      // },
      decoration: InputDecoration(
        hintText: "Company ID",
        contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0),
        hintStyle: TextStyle(fontWeight: FontWeight.w300, color: Colors.blue),
        enabledBorder: new OutlineInputBorder(
            borderSide: new BorderSide(color: Colors.blue)),
        focusedBorder: OutlineInputBorder(
          borderSide: BorderSide(color: Colors.orange),
        ),
      ),
    );

    final user = TextFormField(
      controller: myUserController,
      focusNode: userField,
      autofocus: _currentStep == 1 ? true : false,
      textInputAction: TextInputAction.next,
      // onEditingComplete: () {
      //   print("Editing user complete");
      // },
      // onTap: () {
      //   // if (userField.hasFocus) {
      //   //   print("userField has focus");
      //   // } else {
      //   //   FocusScope.of(context).requestFocus(userField);
      //   // }
      //   setState(() {
      //     _currentStep = 1;
      //   });
      // },
      decoration: InputDecoration(
        hintText: "User ID",
        contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0),
        hintStyle: TextStyle(fontWeight: FontWeight.w300, color: Colors.blue),
        enabledBorder: new OutlineInputBorder(
            borderSide: new BorderSide(color: Colors.blue)),
        focusedBorder: OutlineInputBorder(
          borderSide: BorderSide(color: Colors.orange),
        ),
      ),
    );

    final password = TextFormField(
      controller: myPasswordController,
      focusNode: passwordField,
      autofocus: _currentStep == 2 ? true : false,
      textInputAction: TextInputAction.done,
      // onEditingComplete: () {
      //   print("Editing password complete");
      // },
      // onTap: () {
      //   // if (passwordField.hasFocus) {
      //   //   print("password has focus");
      //   // } else {
      //   //   FocusScope.of(context).requestFocus(passwordField);
      //   // }
      //   setState(() {
      //     _currentStep = 2;
      //   });
      // },
      obscureText: true,
      decoration: InputDecoration(
        hintText: "Password",
        contentPadding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0),
        hintStyle: TextStyle(fontWeight: FontWeight.w300, color: Colors.blue),
        enabledBorder: new OutlineInputBorder(
            borderSide: new BorderSide(color: Colors.blue)),
        focusedBorder: OutlineInputBorder(
          borderSide: BorderSide(color: Colors.orange),
        ),
      ),
    );

    final loginButton = Padding(
      padding: EdgeInsets.symmetric(vertical: 16.0),
      child: Material(
        borderRadius: BorderRadius.circular(30.0),
        shadowColor: Colors.lightBlueAccent.shade100,
        elevation: 5.0,
        child: MaterialButton(
          minWidth: 200.0,
          height: 42.0,
          onPressed: () {
            globals.company = myCompanyController.text;
            globals.user = myUserController.text;
            globals.uid = myUserController.text;
            globals.password = myPasswordController.text;
            logInToServer();
          },
          color: Colors.lightBlueAccent,
          child: Text(
            'Log In',
            style: TextStyle(color: Colors.white),
          ),
        ),
      ),
    );

    final logoutButton = Padding(
      padding: EdgeInsets.symmetric(vertical: 16.0),
      child: Material(
        borderRadius: BorderRadius.circular(30.0),
        shadowColor: Colors.lightBlueAccent.shade100,
        elevation: 5.0,
        child: MaterialButton(
          minWidth: 200.0,
          height: 42.0,
          onPressed: () {
            globals.loggedIn = false;
            Navigator.of(context).pop();
          },
          color: Colors.lightBlueAccent,
          child: Text(
            'Log Out',
            style: TextStyle(color: Colors.white),
          ),
        ),
      ),
    );

    return Center(
      child: Container(
        height: _currentStep == 2 ? 380 : 220,
        width: 400,
        child: Card(
          margin: EdgeInsets.fromLTRB(20.0, 0, 20.0, 0),
          color: Colors.white,
          child: Container(
            child: Stepper(
              type: StepperType.horizontal,
              currentStep: _currentStep,
              onStepTapped: (int step) => setState(() => _currentStep = step),
              onStepContinue: _currentStep < 2
                  ? () {
                      setState(() => _currentStep += 1);
                      changeFocus();
                    }
                  : null,
              onStepCancel: _currentStep > 0
                  ? () => setState(() => _currentStep -= 1)
                  : null,
              steps: [
                Step(
                  title: Text(""),
                  subtitle: Text("Company ID"),
                  content: Column(
                    children: <Widget>[
                      SizedBox(
                        height: 10.0,
                      ),
                      SizedBox(child: company),
                    ],
                  ),
                  isActive: _currentStep >= 0,
                  state: _currentStep == 0
                      ? StepState.complete
                      : _currentStep >= 1
                          ? StepState.complete
                          : StepState.disabled,
                ),
                Step(
                  title: Text(" "),
                  subtitle: Text("User ID"),
                  content: Column(
                    children: <Widget>[
                      SizedBox(
                        height: 10.0,
                      ),
                      SizedBox(child: user),
                    ],
                  ),
                  isActive: _currentStep >= 0,
                  state: _currentStep == 1
                      ? StepState.complete
                      : _currentStep >= 2
                          ? StepState.complete
                          : StepState.disabled,
                ),
                Step(
                  title: Text(" "),
                  subtitle: Text("Password"),
                  content: Column(
                    children: <Widget>[
                      failed ? errorText : Container(child: null),
                      SizedBox(
                        height: 10.0,
                      ),
                      SizedBox(child: logo),
                      SizedBox(
                        height: 28.0,
                      ),
                      SizedBox(child: password),
                      SizedBox(
                        height: 8.0,
                      ),
                      SizedBox(
                        child: loggingIn ? progress : loginButton,
                      ),
                    ],
                  ),
                  isActive: _currentStep >= 0,
                  state: _currentStep == 2
                      ? StepState.complete
                      : _currentStep >= 3
                          ? StepState.complete
                          : StepState.disabled,
                ),
              ],
            ),
          ),
          // child: Column(
          //   children: <Widget>[
          //     failed ? errorText : Container(child: null),
          //     SizedBox(
          //       height: 20.0,
          //     ),
          //     SizedBox(child: logo),
          //     SizedBox(
          //       height: 28.0,
          //     ),
          //     SizedBox(child: company),
          //     SizedBox(
          //       height: 8.0,
          //     ),
          //     SizedBox(child: user),
          //     SizedBox(
          //       height: 8.0,
          //     ),
          //     SizedBox(child: password),
          //     SizedBox(
          //       height: 8.0,
          //     ),
          //     loggingIn ? progress : loginButton,
          //     SizedBox(
          //       height: 200.0,
          //     ),
          //   ],
          // ),
          // ),
        ),
      ),
    );
  }
}

`

**Comment by OlehMarchenko95** [comment]
@Sekaiichi4 your code is working properly, on iPad and iPhone with OS versions 12.3.1 and 12.4

**Comment by OlehMarchenko95** [comment]
Hey, do you really needed 2 weeks to make it?
Maybe I've done something wrong?
[https://github.com/flutter/engine/pull/11390/files](It's yjbanov committed file changes) and except of comment nothing changed, as far as I can see.

**Pull request closed without merging**
