### PR TITLE
Fixed TextField not displaying any input

### PR DESCRIPTION
**Pull request by tauu**
As already reported in https://github.com/flutter/flutter/issues/40039, TextField and TextFormField do not display any text after it is entered. This behaviour is caused by patform_channels not having been switched from using BinaryMessages to ServicesBinding.instance.defaultBinaryMessenger in https://github.com/flutter/flutter_web/commit/36b8f3248cee69e08164ad6a81e8bcd82b31cdfc .

This PR syncs the corresponding changes from https://github.com/flutter/flutter/commit/93c32c4ff667d82136dcc1f8ecef1b0ab993a047#diff-e158ae61bb7a8dd81f710e8f59aa23ca and fixes the issue.

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @ferhatb @yjbanov

**Comment by zTrix** [comment]
Just tried building my app use latest commit of this pull request, and webdev serve it throw the following out, any ideas?

DeepinScreenshot_select-area_20190911023305

**Comment by tauu** [comment]
@zTrix Just to avoid any misunderstanding: you are using the latest commit, which is 
 70a76dda2a1e4c1bf14915ee71ff34324ffaeee2 and not the first one 
( c0c1002f6709c4b13703a6f85cda8e6e229c2e0c ) ? The error is exactly the error I observe, when using the first commit. :-/

**Comment by zTrix** [comment]
@tauu Thanks for your advice, the error happened when using the following config:

```
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      ref: c0c1002f6709c4b13703a6f85cda8e6e229c2e0c
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      ref: c0c1002f6709c4b13703a6f85cda8e6e229c2e0c
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      ref: c0c1002f6709c4b13703a6f85cda8e6e229c2e0c
      path: packages/flutter_web_test
```

**Comment by zTrix** [comment]
I'll do a double check later to ensure the code base is intended.

**Comment by zTrix** [comment]
@tauu just tried again, still with no luck.

Steps:

 - edit `pubspec.yaml`, set ref to `ref: c0c1002f6709c4b13703a6f85cda8e6e229c2e0c`
 - run `flutter packages get`, which shows `flutter_web 0.0.0 from git https://github.com/flutter/flutter_web at c0c100 in packages/flutter_web`
 - check `~/.pub-cache/git/flutter_web-c0c1002f6709c4b13703a6f85cda8e6e229c2e0c/packages/flutter_web/lib/src/services/platform_channel.dart` , code is correct.
 - webdev serve, boom, the error message pops out again: `TypeError: Cannot read property 'defaultBinaryMessenger' of null`

**Comment by knittledan** [comment]
@tauu I've been following this thread and would like to provide input if you don't mind. The `TextField` & `TextFormField` do accept and show input values when I use the git commit hash `70a76dda2a1e4c1bf14915ee71ff34324ffaeee2` you provided.

Here's a [link](https://gitlab.com/knittledan/textfield-input-bug-example) to a very simple flutter_web repo that had broken text fields before using your changes. 


```
➜  sandbox git:(master) flutter doctor -v 
[✓] Flutter (Channel unknown, v1.10.1, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.10.1 at /usr/local/flutter
    • Framework revision ce45c2d3e6 (4 days ago), 2019-09-06 20:11:41 -0400
    • Engine revision b9ce2500d9
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/danielknittle/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

**Comment by zTrix** [comment]
@tauu Sorry, now I get what you mean. I misunderstood timeline order of github, and took the first commit as the latest commit...

**Comment by zTrix** [comment]
Just tried again with ref: 70a76dda2a1e4c1bf14915ee71ff34324ffaeee2, now it works!

**Comment by tauu** [comment]
@knittledan don't mind at all :-) Thanks for the input!
@zTrix no problem. Happy to know that it is working now :)

**Comment by yjbanov** [comment]
Would you be interested in trying the Flutter SDK for your web projects instead? This fork of Flutter will no longer be actively maintained. Getting started instructions are available here: https://flutter.dev/docs/get-started/web

**Comment by tauu** [comment]
Yes :-) Migration of the web project to the Flutter SDK has already started. As soon as I get my other PRs into the SDK, I will move over. ;-)

**Comment by emiliodallatorre** [comment]
This one is definitely working, thanks @tauu, you saved my day!

**Comment by zTrix** [comment]
@yjbanov Flutter SDK for web seems still immature for now, even [http lib is not well supported](https://github.com/flutter/flutter/issues/34858), which drives me continue using this project for a while.

**Comment by yjbanov** [comment]
@zTrix `package:http` should be fully supported. Please file an issue if something works when using `package:flutter_web` but doesn't work when using `package:flutter`.

**Comment by zTrix** [comment]
@yjbanov I'll try it later. Will report issue if found.

**Comment by yjbanov** [comment]
Thanks! Closing this in favor of making it work in the main Flutter SDK (if it doesn't already).

**Pull request closed without merging**
